baseUrl: "https://swiftonserver.com/"
#baseUrl: "http://localhost:3000/"
locale: "en-US"
title: "Swift on server"
navigation:
    - label: "Posts"
      url: "/posts/page/1/"
    - label: "Tags"
      url: "/tags/"
    - label: "Authors"
      url: "/authors/"
    - label: "Newsletter"
      url: "/newsletter/"
      