#!/bin/bash

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --file)
      TOUCAN_FILE="$2"
      shift # past argument
      shift # past value
      ;;
    --slug)
      TOUCAN_SLUG="$2"
      shift # past argument
      shift # past value
      ;;
    --id)
      NEWSLETTER_ID="$2"
      shift # past argument
      shift # past value
      ;;
    --default)
      DEFAULT=YES
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

echo "⏳ Rendering: ${NEWSLETTER_ID}."

CACHE_DIR="./cache/newsletter/"
CACHE_FILE="${CACHE_DIR}${NEWSLETTER_ID}.html"
mkdir -p "${CACHE_DIR}"

if test -f "$CACHE_FILE"; then
   cat "${CACHE_FILE}" >> "${TOUCAN_FILE}"

   echo "✅ Rendering from cache: ${NEWSLETTER_ID}."
   exit 0
fi

curl -k "https://raw.githubusercontent.com/swift-on-server/newsletter/refs/heads/main/issue-${NEWSLETTER_ID}.html" >> "${CACHE_FILE}"
cat "${CACHE_FILE}" >> "${TOUCAN_FILE}"
echo "✅ Rendering: ${NEWSLETTER_ID}."
